cd

IP_ADDRESS=192.168.1.100
PORT=8080
PROJECT_NAME=django_rest
DIRECTORY_NAME=python_project
VENV_NAME=python-venv
DJANGO_VERSION=1.11

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  EXECUTING DJANGO_AUTOSCRIPT  |"
echo "|_______________________________|"
echo ""
sudo apt-get update
export DEBIAN_FRONTEND=noninteractive

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  SETTING UP LANGUAGE  |"
echo "|_______________________|"
echo ""
sudo locale-gen "en_US.UTF-8"
sudo su
echo -e 'LANG="en_US.UTF-8" \n LANGUAGE="en_US.UTF-8" \n LC_ALL="en_US:en_US.UTF-8" \n ' > /etc/default/locale
exit

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  INSTALLING GIT, UNZIP, CURL  |"
echo "|_______________________________|"
echo ""
sudo apt-get install git unzip curl -y

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  CHANGING DEFAULT PYTHON VERSION  |"
echo "|___________________________________|"
echo ""
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  INSTALLING PIP, VENV  |"
echo "|________________________|"
echo ""
sudo apt install python3-pip -y
sudo apt install python3-venv -y
sudo ln -s /usr/bin/pip3 /usr/bin/pip

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  CREATE DIRECTORY & VIRTUAL ENV  |"
echo "|__________________________________|"
echo ""
cd /var/www/html
mkdir $DIRECTORY_NAME
cd $DIRECTORY_NAME
python -m venv $VENV_NAME
source $VENV_NAME/bin/activate

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  INSTALLING DJANGO   |"
echo "|______________________|"
echo ""
pip install django==$DJANGO_VERSION
pip install djangorestframework==3.6.2

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  CREATING DJANGO PROJECT  |"
echo "|___________________________|"
echo ""
django-admin startproject $PROJECT_NAME

# sudo su
# echo `
# \"\"\"
# Django settings for python_api project.

# Generated by \'django-admin startproject\' using Django 3.0.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/3.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/3.0/ref/settings/
# \"\"\"

# import os

# \# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# \# Quick-start development settings - unsuitable \for production
# \# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# \# SECURITY WARNING: keep the secret key used \in production secret\!
# SECRET_KEY = \'ut#y2mj9jf@okazphuf)5%zq0@24lp8a\$0+6\!\!r@\&i(c5_3ej='

# # SECURITY WARNING: don\'t run with debug turned on \in production\!
# DEBUG = True

# ALLOWED_HOSTS = [\'$IP_ADDRESS\']


# \# Application definition

# INSTALLED_APPS = [
#     \'django.contrib.admin\',
#     \'django.contrib.auth\',
#     \'django.contrib.contenttypes\',
#     \'django.contrib.sessions\',
#     \'django.contrib.messages\',
#     \'django.contrib.staticfiles\',
# ]

# MIDDLEWARE = [
#     \'django.middleware.security.SecurityMiddleware\',
#     \'django.contrib.sessions.middleware.SessionMiddleware\',
#     \'django.middleware.common.CommonMiddleware\',
#     \'django.middleware.csrf.CsrfViewMiddleware\',
#     \'django.contrib.auth.middleware.AuthenticationMiddleware\',
#     \'django.contrib.messages.middleware.MessageMiddleware\',
#     \'django.middleware.clickjacking.XFrameOptionsMiddleware\',
# ]

# ROOT_URLCONF = \'python_api.urls\'

# TEMPLATES = [
#     {
#         \'BACKEND\': \'django.template.backends.django.DjangoTemplates\',
#         \'DIRS\': [],
#         \'APP_DIRS\': True,
#         \'OPTIONS\': {
#             \'context_processors\': [
#                 \'django.template.context_processors.debug\',
#                 \'django.template.context_processors.request\',
#                 \'django.contrib.auth.context_processors.auth\',
#                 \'django.contrib.messages.context_processors.messages\',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = \'python_api.wsgi.application\'


# \# Database
# \# https://docs.djangoproject.com/en/3.0/ref/settings/\#databases

# DATABASES = {
#     \'default\': {
#         \'ENGINE\': \'django.db.backends.sqlite3\',
#         \'NAME\': os.path.join(BASE_DIR, \'db.sqlite3\'),
#     }
# }


# \# Password validation
# \# https://docs.djangoproject.com/en/3.0/ref/settings/\#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         \'NAME\': \'django.contrib.auth.password_validation.UserAttributeSimilarityValidator\',
#     },
#     {
#         \'NAME\': \'django.contrib.auth.password_validation.MinimumLengthValidator\',
#     },
#     {
#         \'NAME\': \'django.contrib.auth.password_validation.CommonPasswordValidator\',
#     },
#     {
#         \'NAME\': \'django.contrib.auth.password_validation.NumericPasswordValidator\',
#     },
# ]


# \# Internationalization
# \# https://docs.djangoproject.com/en/3.0/topics/i18n/

# LANGUAGE_CODE = \'en-us\'

# TIME_ZONE = \'UTC\'

# USE_I18N = True

# USE_L10N = True

# USE_TZ = True


# \# Static files (CSS, JavaScript, Images)
# \# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = \'/static/\'
# ` >| /var/www/html/$DIRECTORY_NAME/$PROJECT_NAME/$PROJECT_NAME/settings.py
# exit

echo ""
echo "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|"
echo "|  STARTING DJANGO  |"
echo "|___________________|"
echo ""
cd $PROJECT_NAME
python manage.py runserver $IP_ADDRESS:$PORT